<?xml version="1.0"?>
<package format="3">
  <name>usv_imu_driver</name>
  <version>0.1.0</version>
  <description>Yahboom serial IMU driver and visualization for the USV.</description>
  <maintainer email="hai@example.com">hai</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>imu_filter_madgwick</exec_depend>
  <exec_depend>rviz_imu_plugin</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
